sam <- read.table("data/allGenesGCcontent.tsv", sep="\t", header=T)
s = density(unlist(sam[3]/100))
gc <- read.table("data/allGCpoints.tsv", sep="\t", header=F)
x = density(unlist(gc[1]/100))

png("density.png", width=1000, height=800)
plot(s, main="Theoretical vs. Experimental GC Content KDE")
par(new=TRUE)
plot(x, col='blue', xlab="", yaxt="n")
abline(v=0.5, lwd=2.5, col='red')
axis(4)
legend("topright", c("Theoretical", "Experimental"), lty=c(1,1), lwd=c(2.5,2.5), col=c("black", "blue"))
dev.off()

png("GC_exp_vs_theor.png", width=800, height=600)
plot(s, main="")
par(new=TRUE)
plot(x, col='red', main="", xaxt="n", xlab="", yaxt="n")
abline(v=0.5, lwd=2.5, col="black")
axis(4)
axis(3)
abline(v=0.2, col='grey', lwd=1)
abline(v=0.3, col='grey', lwd=1)
abline(v=0.4, col='grey', lwd=1)
abline(v=0.6, col='grey', lwd=1)
abline(v=0.7, col='grey', lwd=1)
abline(v=0.8, col='grey', lwd=1)
par(new=TRUE)
plot(s, main="", xaxt="n", yaxt="n", xlab="", ylab="", lwd=2)
par(new=TRUE)
plot(x, main="", xaxt="n", yaxt="n", xlab="", ylab="", lwd=1, col='red')
legend("topright", c("Theoretical", "Experimental"), lty=c(1,1), lwd=c(2,1), col=c("black", "red"))
dev.off()
